### ISSUE TITLE
Small screens and windows with scrollify.js

### ISSUE THREAD

**Issue by afuhrtrumpet** [CWDG/design-circle-prototype#32]
When the window gets small, a lot of the text becomes invisible, and can't be seen because of the snappy scrolling. This is a pretty big problem moving forward.

Also, how should we handle this on mobile?

**Comment by J3RN** [comment]
How important is this for the prototype? I can definitely understand this concern with the end-product, but the prototype just has to be demonstrable, right?

Anyhow, my solution would be simple to just display less data on mobile. Instead of having several columns - we could just do one, and so on. This would be acheivable with media queries, like:

``` CSS
@media only screen and max-width(700px) {
  .section2 {
    display: none;
  }
}
```

_P.S. Still not convinced snappy scrolling is a good idea_
